### ISSUE TITLE
[drivetrain] bestTurn needs testing

### ISSUE THREAD

**Issue by NovaAndrom3da** [Team9140/2024#4]
The bestTurn function in SwerveModule.java needs to be tested to ensure it will make the wheels spin the correct directions.

**Comment by TheScientist101** [comment]
It has tests... and it isn't being used...

**Comment by NovaAndrom3da** [comment]
It isn't being used? Is that something landwehr decided? or ...?

**Comment by TheScientist101** [comment]
Yes, Landwehr found that wrapping is already including in motor stuff, so it is unnecessary, but it is there just in case. Also, there are unit tests.

**Comment by NovaAndrom3da** [comment]
Ah okay. If need be I can go ahead and remove that from the repo just so it's not collecting dust :P

**Comment by TheScientist101** [comment]
Landwehr said to keep it just in case. Can I close the issue if there are no other concerns?

**Comment by NovaAndrom3da** [comment]
I don't haev anything else, go ahead
